
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map the container's port 8000 to the host's port 8000
    depends_on:
      - redis  # Wait for the redis service to be ready before starting
      - mongodb
    environment:
      - "TELEGRAM_BOT_KEY={TELEGRAM_BOT_KEY}"
      - "TELEGRAM_CHAT_IP={TELEGRAM_CHAT_ID}"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db  # Docker 볼륨을 MongoDB의 데이터 디렉토리에 마운트합니다.

  redis:
    image: "redis:alpine"  # Use the Redis image from Docker Hub
  
volumes:
  mongo-data: